#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cheetah3
Version  : 3.2.6.post1
Release  : 42
URL      : https://files.pythonhosted.org/packages/23/33/ace0250068afca106c1df34348ab0728e575dc9c61928d216de3e381c460/Cheetah3-3.2.6.post1.tar.gz
Source0  : https://files.pythonhosted.org/packages/23/33/ace0250068afca106c1df34348ab0728e575dc9c61928d216de3e381c460/Cheetah3-3.2.6.post1.tar.gz
Summary  : Cheetah is a template engine and code generation tool
Group    : Development/Tools
License  : MIT
Requires: pypi-cheetah3-bin = %{version}-%{release}
Requires: pypi-cheetah3-filemap = %{version}-%{release}
Requires: pypi-cheetah3-lib = %{version}-%{release}
Requires: pypi-cheetah3-license = %{version}-%{release}
Requires: pypi-cheetah3-python = %{version}-%{release}
Requires: pypi-cheetah3-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
It can be used standalone or combined with other tools and frameworks. Web
        development is its principle use, but Cheetah is very flexible and
        is also being used to generate C++ game code, Java, sql, form emails
        and even Python code.
        
        It's a fork of the original CheetahTemplate library.
        
        Documentation
        ================================================================================
        For a high-level introduction to Cheetah please refer to the User's Guide

%package bin
Summary: bin components for the pypi-cheetah3 package.
Group: Binaries
Requires: pypi-cheetah3-license = %{version}-%{release}
Requires: pypi-cheetah3-filemap = %{version}-%{release}

%description bin
bin components for the pypi-cheetah3 package.


%package filemap
Summary: filemap components for the pypi-cheetah3 package.
Group: Default

%description filemap
filemap components for the pypi-cheetah3 package.


%package lib
Summary: lib components for the pypi-cheetah3 package.
Group: Libraries
Requires: pypi-cheetah3-license = %{version}-%{release}
Requires: pypi-cheetah3-filemap = %{version}-%{release}

%description lib
lib components for the pypi-cheetah3 package.


%package license
Summary: license components for the pypi-cheetah3 package.
Group: Default

%description license
license components for the pypi-cheetah3 package.


%package python
Summary: python components for the pypi-cheetah3 package.
Group: Default
Requires: pypi-cheetah3-python3 = %{version}-%{release}

%description python
python components for the pypi-cheetah3 package.


%package python3
Summary: python3 components for the pypi-cheetah3 package.
Group: Default
Requires: pypi-cheetah3-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(cheetah3)

%description python3
python3 components for the pypi-cheetah3 package.


%prep
%setup -q -n Cheetah3-3.2.6.post1
cd %{_builddir}/Cheetah3-3.2.6.post1
pushd ..
cp -a Cheetah3-3.2.6.post1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672262701
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cheetah3
cp %{_builddir}/Cheetah3-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cheetah3/a7186cce21fd72616b0fde6964715d4c16ea0c19 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cheetah
/usr/bin/cheetah-analyze
/usr/bin/cheetah-compile

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-cheetah3

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cheetah3/a7186cce21fd72616b0fde6964715d4c16ea0c19

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
